include config.mk

DEF_FILE_DIR   = -DRB_DEFAULT_FILE_DIRECTORY=\"/expdata/dragon/DAQ_test/\"
DEF_SAVE_DIR   = -DRB_DEFAULT_SAVE_DIRECTORY=\"/expdata/dragon/DAQ_test/rootfiles\"
DEF_CONFIG_DIR = -DRB_DEFAULT_CONFIG_DIRECTORY=\"/Users/dragon/packages/rootbeer/config\"
DEFAULTS       = $(DEF_FILE_DIR) $(DEF_SAVE_DIR) $(DEF_CONFIG_DIR)

### Variable definitions
SRC   = $(PWD)/src
OBJ   = $(PWD)/obj
CINT  = $(PWD)/cint
RBLIB = $(PWD)/lib

INCFLAGS = -I$(SRC)
# OPTIMIZE = -O3
# DEBUG    = -DDEBUG
#-DRB_LOGGING

UNAME = $(shell uname)
ifeq ($(UNAME),Darwin)
SOFLAGS = -dynamiclib -single_module -undefined dynamic_lookup
FPIC    =
RPATH   =
else
SOFLAGS = -shared
FPIC    = -fPIC
RPATH   = -Wl,-rpath,$(ROOTSYS)/lib -Wl,-rpath,$(PWD)/lib
endif

CXXFLAGS += $(INCFLAGS) $(DEFAULTS)
# CXXFLAGS = $(DEBUG) -ggdb $(OPTIMIZE) $(INCFLAGS) $(ROOTCFLAGS) $(DEFAULTS)
# CXXFLAGS += -v
CINTFLAGS = $(filter-out ($(ROOTCFLAGS)), $(CXXFLAGS))

LDFLAGS = $(SOFLAGS) $(FPIC) $(RPATH)
LIBS    = $(ROOTLIBS) -L$(PWD)/lib

CXX += $(CXXFLAGS) $(AUXFLAGS)

LD   = $(CXX) $(LDFLAGS)


#### MAIN PROGRAM ####
all:  $(MAKE_ALL)

#### ROOTBEER LIBRARY ####
SOURCES = $(shell ls $(SRC)/*.cxx $(SRC)/hist/*.cxx)

OBJECTS = $(OBJ)/mxml/mxml.o $(OBJ)/mxml/strlcpy.o $(OBJ)/hist/Hist.o $(OBJ)/hist/Manager.o \
$(OBJ)/Formula.o $(OBJ)/ClassFormula.o $(OBJ)/ClassData.o $(OBJ)/Error.o \
$(OBJ)/Data.o $(OBJ)/Event.o $(OBJ)/Attach.o $(OBJ)/Canvas.o $(OBJ)/WriteConfig.o \
$(OBJ)/Rint.o $(OBJ)/Signals.o $(OBJ)/Rootbeer.o $(OBJ)/Gui.o $(OBJ)/HistGui.o \
$(OBJ)/TGSelectDialog.o $(OBJ)/TGDivideSelect.o $(OBJ)/Main.o

HEADERS = $(SRC)/Main.hxx $(SRC)/Rootbeer.hxx $(SRC)/Rint.hxx $(SRC)/Data.hxx $(SRC)/Buffer.hxx \
$(SRC)/Attach.hxx $(SRC)/Event.hxx $(SRC)/Signals.hxx $(SRC)/Formula.hxx $(SRC)/ClassFormula.hxx \
$(SRC)/ClassData.hxx $(SRC)/utils/LockingPointer.hxx $(SRC)/utils/Mutex.hxx $(SRC)/utils/Error.hxx \
$(SRC)/hist/Hist.hxx $(SRC)/hist/Visitor.hxx $(SRC)/hist/Manager.hxx $(SRC)/TGSelectDialog.h \
$(SRC)/TGDivideSelect.h $(SRC)/HistGui.hxx $(SRC)/Gui.hxx $(SRC)/utils/*.h* $(SRC)/mxml/*.hxx


RBlib: $(RBLIB)/libRootbeer.so

$(RBLIB)/libRootbeer.so: $(RBLIB)/RBDictionary.cxx $(OBJECTS)
	$(LD) $(OBJECTS) $(RBLIB)/RBDictionary.cxx $(LIBS) \
-o $@ \

$(OBJ)/midas/MidasBuffer.o: $(SRC)/midas/MidasBuffer.cxx $(RBLIB)/MidasDict.cxx $(RBLIB)/RBDictionary.cxx
	$(CXX) $(FPIC) $(MIDASFLAGS) -c $< \
-o $@  \

$(OBJ)/midas/%.o: $(SRC)/midas/%.cxx $(RBLIB)/MidasDict.cxx
	$(CXX) $(FPIC) $(MIDASFLAGS) -c $< \
-o $@  \

$(OBJ)/mxml/%.o: $(SRC)/mxml/%.cxx $(SRC)/mxml/*.hxx $(RBLIB)/RBDictionary.hxx
	$(CXX) $(FPIC) -c $< \
-o $@  \

$(OBJ)/%.o: $(SRC)/utils/%.cxx $(RBLIB)/RBDictionary.cxx
	$(CXX) $(FPIC) -c $< \
-o $@  \

$(OBJ)/%.o: $(SRC)/%.cxx $(RBLIB)/RBDictionary.cxx
	$(CXX) $(FPIC) -c $< \
-o $@  \

RBdict: $(RBLIB)/RBDictionary.cxx

$(RBLIB)/RBDictionary.cxx:  $(HEADERS) $(CINT)/Linkdef.h \
$(SRC)/utils/Mutex.hxx $(SRC)/utils/LockingPointer.hxx $(SRC)/utils/Assorted.hxx $(SRC)/hist/*.hxx
	$(ROOTCINT) -f $@ -c $(CINTFLAGS) -p $(HEADERS) $(CINT)/Linkdef.h \

### librbMidas.so ###
MIDAS_SOURCES  = $(shell ls $(SRC)/midas/*.cxx)
MIDAS_HEADERS1 = $(shell ls $(SRC)/midas/*.h $(SRC)/midas/*.hxx)
MIDAS_HEADERS  = $(MIDAS_HEADERS1:$(SRC)/midas/MidasLinkdef.h= )
MIDAS_OBJECTS0 = $(MIDAS_SOURCES:$(SRC)/midas/TMidasOnline.cxx= )
MIDAS_OBJECTS1 = $(MIDAS_OBJECTS0:.cxx=.o)
MIDAS_OBJECTS := $(addprefix $(OBJ)/midas/, $(notdir $(MIDAS_OBJECTS1)))

# optional MIDAS libraries
UNAME=$(shell uname)
ifdef MIDASSYS
MIDASFLAGS=-DMIDASSYS -I$(MIDASSYS)/include -Dextname
ifeq ($(UNAME),Darwin)
MIDASFLAGS +=-DOS_DARWIN
else
MIDASFLAGS +=-DOS_LINUX
endif
ifdef MIDAS_SERVER_HOST
MIDASFLAGS += -DMIDAS_SERVER_HOST=\"$(MIDAS_SERVER_HOST)\"
endif
ifdef MIDAS_EXPT_NAME
MIDASFLAGS += -DMIDAS_EXPT_NAME=\"$(MIDAS_EXPT_NAME)\"
endif
endif

librbMidas: $(RBLIB)/librbMidas.so

$(RBLIB)/librbMidas.so: $(MIDAS_OBJECTS) $(RBLIB)/MidasDict.cxx
	$(LD) $(MIDAS_OBJECTS) $(RBLIB)/MidasDict.cxx \
	-o $@ \

$(RBLIB)/MidasDict.cxx: $(MIDAS_HEADERS) $(SRC)/midas/MidasLinkdef.h
	$(ROOTCINT) -f $@ -c $(CINTFLAGS) -p $(MIDAS_HEADERS) $(SRC)/midas/MidasLinkdef.h \


#### REMOVE EVERYTHING GENERATED BY MAKE ####

clean:
	rm -f $(RBLIB)/*.so $(RBLIB)/*.dylib rootbeer $(RBLIB)/*Dict*.h $(RBLIB)/*Dict*.cxx $(OBJ)/*.o $(OBJ)/*/*.o

midasclean:
	rm -f $(RBLIB)/librbMidas.so.devl $(RBLIB)/MidasDict.* $(OBJ)/midas/*.o

#### FOR DOXYGEN ####

doc:
	doxygen doxygen/Doxyfile
